source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'sqlite3'

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
# gem 'coffee-rails', '~> 4.0.0'
gem "haml"

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'sdoc', '~> 0.4.0',          group: :doc


gem 'spring',        group: :development

group :evelopment, :test do
  gem "guard-rspec"
  gem "rspec-rails"
  gem "capybara"
  gem 'guard-minitest'
  gem 'minitest-reporters'
end